services:
  api:
    image: mcr.microsoft.com/dotnet/aspnet
    working_dir: /api
    entrypoint:
      - dotnet
      - PlaygroundApi.dll
    container_name: playground-api
    networks:
      - playground-network
    volumes:
      - type: bind
        source: dist/api
        target: /api
    depends_on:
      - db
  db:
    image: postgres
    container_name: playground-db
    environment:
      POSTGRES_PASSWORD: pwd1234
    networks:
      - playground-network
  site:
    image: nginx
    container_name: playground-site
    ports:
      - "80:80"
    networks:
      - playground-network
    volumes:
      - type: bind
        source: dist/app
        target: /site
      - type: bind
        source: docker/playground-site.conf
        target: /etc/nginx/conf.d/default.conf
networks:
  playground-network: {}